"""fopost — official Python SDK for the FoPost API.

Quick start::

    from fopost import Fopost

    client = Fopost(api_key="fp_...")

    accounts = client.accounts.list(workspace_id="9b2f6c1e-...")
    post = client.posts.create(
        workspace_id="9b2f6c1e-...",
        content="Hello from Python",
        accounts=[a.id for a in accounts],
    )
    client.posts.publish(post.id)
"""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from ._http import DEFAULT_BASE_URL
from .client import Fopost
from .errors import (
    AuthenticationError,
    FopostError,
    NotFoundError,
    PaymentRequiredError,
    PermissionDeniedError,
    RateLimitError,
)
from .models import (
    PLATFORMS,
    POST_STATUSES,
    AccountGroup,
    AccountMove,
    AccountRename,
    Ad,
    AdAccountTree,
    AdCampaign,
    AdCampaignNode,
    AdConnection,
    AdCreative,
    AdInsights,
    AdInsightsReport,
    AdSet,
    AdSetNode,
    AdSource,
    AiCreditBalance,
    AiCredits,
    Audience,
    AudienceFilter,
    AudiencesResult,
    BoostablePost,
    Broadcast,
    BroadcastCounts,
    BroadcastRecipient,
    BulkAdStatusResult,
    CaptionResult,
    Contact,
    ContactChannel,
    ContactConversation,
    ContactField,
    ContactImportResult,
    ContactImportSkip,
    ContactLabel,
    ContentBlock,
    ContentSignal,
    ConversationAnalytics,
    ConversationAnalyticsRow,
    Delivery,
    Enrollment,
    ExternalAd,
    FeedLead,
    InboxAccount,
    InboxAccountRef,
    InboxApproval,
    InboxAttachment,
    InboxConversation,
    InboxItem,
    InboxPlatform,
    InboxPostContext,
    InboxRefreshResult,
    InboxReplyResult,
    InboxStartConversationResult,
    InboxThread,
    InsightsMetrics,
    InsightsRow,
    Label,
    Lead,
    LeadForm,
    LeadFormDetail,
    LeadFormSource,
    LeadPage,
    LeadPageSubscription,
    LeadsFeedPage,
    LeadsPage,
    MediaItem,
    NetworkAd,
    Page,
    PageMeta,
    Platform,
    Post,
    PostAccount,
    PostStatus,
    PresignedUpload,
    ReachEstimate,
    RepurposeResult,
    RewriteResult,
    RewriteVariant,
    Sequence,
    SequenceEnrollmentCounts,
    SequenceStep,
    SlackChannel,
    SlackIdentity,
    SlackMember,
    SocialAccount,
    TargetingOption,
    TelegramBotCommand,
    TelegramBotCommands,
    TelegramConnectCode,
    TelegramConnectStatus,
    ValidateLengthCheck,
    ValidateLengthResult,
    ValidateMediaResult,
    ValidatePlatformCheck,
    ValidatePostResult,
    Workspace,
)

try:
    __version__ = _pkg_version("fopost")
except PackageNotFoundError:  # running from a source tree
    __version__ = "0.0.0"

#: Alias for people arriving from the TypeScript SDK, where the class is `FoPost`.
FoPost = Fopost

__all__ = [
    "DEFAULT_BASE_URL",
    "PLATFORMS",
    "POST_STATUSES",
    "AccountGroup",
    "AccountMove",
    "AccountRename",
    "Ad",
    "AdConnection",
    "AdInsights",
    "AdSource",
    "AiCreditBalance",
    "AiCredits",
    "Audience",
    "AudiencesResult",
    "AuthenticationError",
    "BoostablePost",
    "CaptionResult",
    "ContentBlock",
    "Delivery",
    "ExternalAd",
    "FoPost",
    "Fopost",
    "FopostError",
    "InboxAccount",
    "InboxAccountRef",
    "InboxApproval",
    "InboxAttachment",
    "InboxConversation",
    "AudienceFilter",
    "Broadcast",
    "BroadcastCounts",
    "BroadcastRecipient",
    "Contact",
    "ContactChannel",
    "ContactConversation",
    "ContactField",
    "ContactImportResult",
    "ContactImportSkip",
    "ContactLabel",
    "ConversationAnalytics",
    "ConversationAnalyticsRow",
    "Enrollment",
    "Sequence",
    "SequenceEnrollmentCounts",
    "SequenceStep",
    "InboxItem",
    "InboxPlatform",
    "InboxPostContext",
    "InboxRefreshResult",
    "InboxReplyResult",
    "InboxStartConversationResult",
    "InboxThread",
    "Label",
    "Lead",
    "LeadForm",
    "LeadFormSource",
    "LeadsPage",
    "MediaItem",
    "NotFoundError",
    "Page",
    "PageMeta",
    "PaymentRequiredError",
    "PermissionDeniedError",
    "Platform",
    "Post",
    "PostAccount",
    "PostStatus",
    "PresignedUpload",
    "RateLimitError",
    "RepurposeResult",
    "RewriteResult",
    "RewriteVariant",
    "SlackChannel",
    "SlackIdentity",
    "SlackMember",
    "SocialAccount",
    "TargetingOption",
    "TelegramBotCommand",
    "TelegramBotCommands",
    "TelegramConnectCode",
    "TelegramConnectStatus",
    "ValidateLengthCheck",
    "ValidateLengthResult",
    "ValidateMediaResult",
    "ValidatePlatformCheck",
    "ValidatePostResult",
    "ContentSignal",
    "Workspace",
    "__version__",
    "AdAccountTree",
    "AdCampaign",
    "AdCampaignNode",
    "AdCreative",
    "AdInsightsReport",
    "AdSet",
    "AdSetNode",
    "BulkAdStatusResult",
    "FeedLead",
    "InsightsMetrics",
    "InsightsRow",
    "LeadFormDetail",
    "LeadPage",
    "LeadPageSubscription",
    "LeadsFeedPage",
    "NetworkAd",
    "ReachEstimate",
]
